/**
 * Feature: e1-editorial-ui-overhaul, Property 7: NotchedSection fallback
 * geometry invariants.
 *
 * For any viewport-like bounding box (W, H) drawn from
 * `fc.tuple(fc.integer({min:320,max:2560}), fc.integer({min:200,max:4000}))`,
 * the silhouette path generated by `buildSilhouettePath(W, H)` SHALL:
 *   - expose exactly four rounded outer-corner arcs of radius 40 (±0.5 px),
 *   - expose exactly two inward concave notch arcs centered at x = W/2,
 *   - measure each notch at 220 × 55 px width × depth within ±2 px,
 *   - place the top notch on y = 0 with sweep-flag 1 (concave downward
 *     into the shape) and the bottom notch on y = H with sweep-flag 0
 *     (concave upward into the shape).
 *
 * These invariants are what the `<NotchedSection>` SVG fallback writes to
 * its `<clipPath>` `d` attribute on every `ResizeObserver` tick, so the
 * test exercises the pure path generator directly without rendering.
 *
 * Validates: Requirement 7.8 (with 7.1, 7.2, 7.3, 7.4 geometry)
 */

import fc from "fast-check";
import {
  buildSilhouettePath,
  OUTER_RADIUS,
  NOTCH_WIDTH,
  NOTCH_DEPTH,
} from "../NotchedSection";

/**
 * Tiny SVG path parser. Understands only the commands emitted by
 * `buildSilhouettePath` — `M`, `L`, `A`, `Z` — all in absolute form. For
 * each `A` command we record the implicit starting point (previous
 * command's endpoint) alongside the arc parameters so the geometry
 * assertions can inspect both ends of the arc without re-tracing.
 *
 * @param {string} d SVG path `d` attribute
 * @returns {{cmd: string, args: number[], from?: {x:number, y:number}, to?: {x:number, y:number}}[]}
 */
function parsePath(d) {
  const ops = [];
  const re = /([MLAZ])\s*([^MLAZ]*)/g;
  let match;
  while ((match = re.exec(d)) !== null) {
    const cmd = match[1];
    const args = match[2]
      .trim()
      .split(/[\s,]+/)
      .filter((s) => s.length > 0)
      .map(Number);
    ops.push({ cmd, args });
  }
  // Second pass: track cursor so each A records (from, to).
  let cx = 0;
  let cy = 0;
  for (const op of ops) {
    switch (op.cmd) {
      case "M":
      case "L": {
        cx = op.args[0];
        cy = op.args[1];
        break;
      }
      case "A": {
        // A rx ry x-axis-rotation large-arc-flag sweep-flag x y
        const [, , , , , ex, ey] = op.args;
        op.from = { x: cx, y: cy };
        op.to = { x: ex, y: ey };
        cx = ex;
        cy = ey;
        break;
      }
      case "Z":
      default:
        break;
    }
  }
  return ops;
}

describe("NotchedSection — Property 7: fallback geometry invariants", () => {
  /**
   * Property 7. Feature: e1-editorial-ui-overhaul, Property 7.
   *
   * Validates: Requirement 7.8 (with 7.1, 7.2, 7.3, 7.4 geometry)
   */
  it("generates four radius-40 outer corners and two W/2-centered notches at 220 × 55 px", () => {
    fc.assert(
      fc.property(
        fc.tuple(
          fc.integer({ min: 320, max: 2560 }),
          fc.integer({ min: 200, max: 4000 })
        ),
        ([W, H]) => {
          const d = buildSilhouettePath(W, H);
          const ops = parsePath(d);
          const arcs = ops.filter((op) => op.cmd === "A");

          // ---------------------------------------------------------------
          // Arc inventory: two notches + four corners = six total.
          // ---------------------------------------------------------------
          expect(arcs.length).toBe(6);

          // ---------------------------------------------------------------
          // Classify arcs by rx/ry fingerprints. Corners are (40, 40); the
          // notches are (NOTCH_WIDTH/2, NOTCH_DEPTH) = (110, 55).
          // Tolerances: ±0.5 px on corner radii; ±1 px on notch half-width
          // and ±2 px on notch depth (keeps notch width within ±2 of 220
          // and depth within ±2 of 55 per Property 7).
          // ---------------------------------------------------------------
          const cornerArcs = arcs.filter((op) => {
            const [rx, ry] = op.args;
            return (
              Math.abs(rx - OUTER_RADIUS) <= 0.5 &&
              Math.abs(ry - OUTER_RADIUS) <= 0.5
            );
          });
          const notchArcs = arcs.filter((op) => {
            const [rx, ry] = op.args;
            return (
              Math.abs(2 * rx - NOTCH_WIDTH) <= 2 &&
              Math.abs(ry - NOTCH_DEPTH) <= 2
            );
          });

          expect(cornerArcs.length).toBe(4);
          expect(notchArcs.length).toBe(2);

          // ---------------------------------------------------------------
          // Corners sit on the four box corners. Outer endpoints must be
          // within r of exactly one horizontal edge (x == 0 or x == W) and
          // one vertical edge (y == 0 or y == H). We assert each corner's
          // union of {from, to} endpoints touches two distinct axis
          // extremes so all four corners are accounted for.
          // ---------------------------------------------------------------
          const cornersSeen = new Set();
          for (const arc of cornerArcs) {
            const xs = [arc.from.x, arc.to.x];
            const ys = [arc.from.y, arc.to.y];
            const touchesLeft = xs.some((x) => x === 0);
            const touchesRight = xs.some((x) => x === W);
            const touchesTop = ys.some((y) => y === 0);
            const touchesBottom = ys.some((y) => y === H);
            // Each corner arc touches exactly one horizontal edge AND one
            // vertical edge.
            expect(Number(touchesLeft) + Number(touchesRight)).toBe(1);
            expect(Number(touchesTop) + Number(touchesBottom)).toBe(1);
            const key =
              (touchesLeft ? "L" : "R") + (touchesTop ? "T" : "B");
            cornersSeen.add(key);
          }
          expect(cornersSeen.size).toBe(4); // TL, TR, BL, BR

          // ---------------------------------------------------------------
          // Notch geometry. One notch lives on y = 0, the other on y = H.
          // Each is centered at x = W/2 and carries the correct sweep flag
          // for an inward concavity.
          // ---------------------------------------------------------------
          const topNotch = notchArcs.find(
            (op) => op.from.y === 0 && op.to.y === 0
          );
          const bottomNotch = notchArcs.find(
            (op) => op.from.y === H && op.to.y === H
          );
          expect(topNotch).toBeDefined();
          expect(bottomNotch).toBeDefined();

          for (const arc of [topNotch, bottomNotch]) {
            // Centered at W/2 (arc spans [W/2 - rx, W/2 + rx] in either
            // traversal direction so midpoint of endpoints === W/2).
            const midX = (arc.from.x + arc.to.x) / 2;
            expect(Math.abs(midX - W / 2)).toBeLessThanOrEqual(0.5);

            // Width: |end.x - start.x| should equal 2*rx within ±2 px of
            // NOTCH_WIDTH (220).
            const width = Math.abs(arc.to.x - arc.from.x);
            expect(Math.abs(width - NOTCH_WIDTH)).toBeLessThanOrEqual(2);

            // Depth: ry is the vertical semi-axis of the elliptical arc,
            // which equals notch depth because the arc spans the full
            // horizontal diameter (end.x - start.x === 2*rx).
            const ry = arc.args[1];
            expect(Math.abs(ry - NOTCH_DEPTH)).toBeLessThanOrEqual(2);
          }

          // sweep-flag indices in A args: [rx, ry, rot, large, sweep, x, y]
          // Top notch is traversed left → right along y = 0; sweep = 1
          // curves the arc into the shape (positive y / downward on screen).
          expect(topNotch.args[4]).toBe(1);
          // Bottom notch is traversed right → left along y = H; sweep = 0
          // curves the arc into the shape (negative y / upward on screen).
          expect(bottomNotch.args[4]).toBe(0);
        }
      ),
      { numRuns: 100 }
    );
  });
});
